######################################
#
# Voltseon's Trainer Generator
#
######################################
# Version 1.0
######################################
#
# Configuration
#
######################################

# Common event that plays before the battle starts
RT_COMMON_EVENT_ID = 64

# The odds of the trainer using a gender neutral name
GENDER_NEUTRAL_CHANCE = 25 # Out of 100

# Force the pokemon to be unevolved below a certain level (to disable put 0)
FORCED_UNEVOLVED_LEVEL = 20

# Force the pokemon to be fully evolved after a certain level (to disable put 100)
FORCED_FULLY_EVOLVED_LEVEL = 100

# Whether to use the species blacklist or whitelist
# true = blacklist, false = whitelist
USE_SPECIES_BLACKLIST = true

# An array of lose texts
LOSE_TEXTS = [
  "Aww man, I thought I had a chance.",
  "I suppose I am the loser.",
  "Wow, you're pretty strong!",
  "Those were some cool moves!",
  "Pfft. Before I could get serious, I lost!",
  "OK! I give up!",
  "I lost. I lost!",
  "I'm glad I got to see your Pokémon!",
  "Hmm. This is disappointing.",
  "Ow, ow, ow!",
  "Just as I thought, you're tough!",
  "Argh, I can't do anymore...",
  "Looks like you're the stronger one...",
  "Way to go!",
  "That's too bad.",
  "Just what I expected.",
  "Oh... That's disappointing!",
  "That's odd.",
  "...Humph! Are you happy you won?",
  "Tch! I tried to rush things...",
  "Argh! You're too strong!",
  "I was not expecting to lose that hard.",
  "Aack! My Pokémon!",
  "I was no match...",
  "Didn't I train enough?",
  "I see. So you can battle that way.",
  "That's strange. I won before.",
  "I was whipped...",
  "...Hmmm...",
  "Yow! You're too strong!",
  "This can't be true!",
  "Gaah!",
  "Yikes! Not fast enough!",
  "What an amazing battle!",
  "Phew...",
  "Pretty impressive! I'm sure you can go anywhere with that skill!",
  "You're too much!",
  "Good battle!",
  "Gwa ha ha! I lost.",
  "I can't move anymore...",
  "That's shocking!",
  "Whew... Good battle.",
  "Oh, yikes! We lost!",
  "Whatever!",
  "Heh, I guess I didn't try hard enough.",
  "I lost that one!",
  "Gulp! This is a bleak moment.",
  "Mercy!",
  "Tch! I took you too lightly!",
  "Uh-oh! I was also sunk by indecision!",
  "Ayeeee!",
  "Uww... I blew it.",
  "Impresive...",
  "We give up! You're the winner!",
  "Looks like we underestimated you...",
  "Oh, so close! I almost had you!",
  "...did I win?",
  "Oh... I lost... you're not weak...",
  "Oh, dear! I wanted to win!",
  "Yikes! Sorry!",
  "... ... I'll go train some more...",
  "Yaha! I lost!",
  "I was no match...",
  "Uwahauwaha!",
  "Nyuraahahhaah!",
  "You never saw me...",
  "Uwaaah! Eeek!",
  "Grr! I lost that...",
  "Oh... I lost...",
  "Peace--even though I lost!",
  "I did not expect to lose this battle.",
  "Ugh, why do I always keep losing these battles?",
  "No way!",
  "Aww, darn it!",
  "You cheated! It's that simple.",
  "I should've guessed you would cheat.",
  "I thought I was prepared for anything!",
  "I can't accept defeat like this...",
  "I knew you would win.",
  "Wow, you're too good!",
  "This can't be happening.",
  "Wow! You're super impressive.",
  "Hang on, this makes no sense...",
  "How did this happen? I'm smarter than this!",
  "Wait a minute!",
  "... Huh?"
]

# An array of available Pokémon
SPECIES_WHITELIST = [
  :BULBASAUR, :IVYSAUR, :VENUSAUR,
  :CHARMANDER, :CHARMELEON, :CHARIZARD,
  :SQUIRTLE, :WARTORTLE, :BLASTOISE,
  :CATERPIE, :METAPOD, :BUTTERFREE,
  :WEEDLE, :KAKUNA, :BEEDRILL,
  :PIDGEY, :PIDGEOTTO, :PIDGEOT,
  :RATTATA, :RATICATE,
  :SPEAROW, :FEAROW,
  :EKANS, :ARBOK,
  :PIKACHU, :RAICHU,
  :SANDSHREW, :SANDSLASH,
  :NIDORANfE, :NIDORINA, :NIDOQUEEN,
  :NIDORANmA, :NIDORINO, :NIDOKING,
  :CLEFAIRY, :CLEFABLE,
  :VULPIX, :NINETALES,
  :JIGGLYPUFF, :WIGGLYTUFF,
  :ZUBAT, :GOLBAT,
  :ODDISH, :GLOOM, :VILEPLUME,
  :PARAS, :PARASECT,
  :VENONAT, :VENOMOTH,
  :DIGLETT, :DUGTRIO,
  :MEOWTH, :PERSIAN,
  :PSYDUCK, :GOLDUCK,
  :MANKEY, :PRIMEAPE,
  :GROWLITHE, :ARCANINE,
  :POLIWAG, :POLIWHIRL, :POLIWRATH,
  :ABRA, :KADABRA, :ALAKAZAM,
  :MACHOP, :MACHOKE, :MACHAMP,
  :BELLSPROUT, :WEEPINBELL, :VICTREEBEL,
  :TENTACOOL, :TENTACRUEL,
  :GEODUDE, :GRAVELER, :GOLEM,
  :PONYTA, :RAPIDASH,
  :SLOWPOKE, :SLOWBRO,
  :MAGNEMITE, :MAGNETON,
  :FARFETCHD,
  :DODUO, :DODRIO,
  :SEEL, :DEWGONG,
  :GRIMER, :MUK,
  :SHELLDER, :CLOYSTER,
  :GASTLY, :HAUNTER, :GENGAR,
  :ONIX,
  :DROWZEE, :HYPNO,
  :KRABBY, :KINGLER,
  :VOLTORB, :ELECTRODE,
  :EXEGGCUTE, :EXEGGUTOR,
  :CUBONE, :MAROWAK,
  :HITMONLEE, :HITMONCHAN,
  :LICKITUNG,
  :KOFFING, :WEEZING,
  :RHYHORN, :RHYDON,
  :CHANSEY,
  :TANGELA,
  :KANGASKHAN,
  :HORSEA, :SEADRA,
  :GOLDEEN, :SEAKING,
  :STARYU, :STARMIE,
  :MRMIME,
  :SCYTHER,
  :JYNX,
  :ELECTABUZZ,
  :MAGMAR,
  :PINSIR,
  :TAUROS,
  :MAGIKARP, :GYARADOS,
  :LAPRAS,
  :DITTO,
  :EEVEE, :VAPOREON, :JOLTEON, :FLAREON,
  :PORYGON,
  :OMANYTE, :OMASTAR,
  :KABUTO, :KABUTOPS,
  :AERODACTYL,
  :DRATINI, :DRAGONAIR, :DRAGONITE
]

# An array of banned Pokémon
SPECIES_BLACKLIST = [
  :ZAPDOS, :MOLTRES, :ARTICUNO,
  :ZAPDOS_1, :MOLTRES_1, :ARTICUNO_1,
  :RAIKOU, :SUICUNE, :ENTEI,
  :REGICE, :REGISTEEL, :REGIROCK,
  :LATIAS, :LATIOS,
  :UXIE, :MESPRIT, :AZELF,
  :HEATRAN,
  :REGIGIGAS,
  :CRESSELIA,
  :COBALION, :TERRAKION, :VIRIZION,
  :TORNADUS, :THUNDURUS, :LANDORUS,
  :TORNADUS_1, :THUNDURUS_1, :LANDORUS_1,
  :TYPENULL, :SILVALLY,
  :TAPUKOKO, :TAPULELE, :TAPUBULU, :TAPUFINI,
  :NIHILEGO, :BUZZWOLE, :PHEROMOSA,
  :XURKITREE, :CELESTEELA, :KARTANA,
  :GUZZLORD,
  :POIPOLE, :NAGANADEL,
  :STAKATAKA, :BLACEPHALON,
  :KUBFU,
  :URSHIFU, :URSHIFU_1,
  :REGIELEKI, :REGIDRAGO,
  :GLASTRIER, :SPECTRIER,
  :ENAMORUS, :ENAMORUS_1,
  :MEWTWO,
  :LUGIA, :HOOH,
  :GROUDON, :KYOGRE, :RAYQUAZA,
  :DIALGA, :PALKIA, :GIRATINA,
  :RESHIRAM, :ZEKROM,
  :KYUREM, :KYUREM_1, :KYUREM_2,
  :KYUREM_3, :KYUREM_4,
  :XERNEAS, :YVELTAL, :ZYGARDE,
  :XERNEAS_1, 
  :ZYGARDE_1, :ZYGARDE_2, :ZYGARDE_3,
  :COSMOG, :COSMOEM, :SOLGALEO, :LUNALA,
  :NECROZMA, :NECROZMA_1, :NECROZMA_2,
  :ZACIAN, :ZAMAZENTA,
  :ZACIAN_1, :ZAMAZENTA_1,
  :ETERNATUS,
  :CALYREX, :CALYREX_1, :CALYREX_2,
  :MEW,
  :CELEBI,
  :JIRACHI,
  :DEOXYS, :DEOXYS_1, :DEOXYS_2, :DEOXYS_3,
  :PHIONE, :MANAPHY,
  :DARKRAI,
  :SHAYMIN, :SHAYMIN_1,
  :VICTINI,
  :KELDEO, :KELDEO_1,
  :MELOETTA, :MELOETTA_1,
  :GENESECT, :GENESECT_1, :GENESECT_2, :GENESECT_3, :GENESECT_4,
  :DIANCIE,
  :HOOPA, :HOOPA_1,
  :VOLCANION,
  :MAGEARNA, :MAGEARNA_1,
  :MARSHADOW,
  :ZERAORA,
  :MELTAN, :MELMETAL
]

# An array of Pokémon that are 100% BANNED
SPECIES_TRUEBLACKLIST = [
  :VENUSAUR_1, :CHARIZARD_1, :CHARIZARD_2, :BLASTOISE_1,
  :BEEDRILL_1, :PIDGEOT_1, :ALAKAZAM_1,
  :SLOWBRO_2, :GENGAR_1, :KANGASKHAN_1,
  :PINSIR_1, :GYARADOS_1, :AERODACTYL_1,
  :MEWTWO_1, :MEWTWO_2,
  :AMPHAROS_1, :STEELIX_1, :SCIZOR_1,
  :HERACROSS_1, :HOUNDOOM_1, :TYRANITAR_1,
  :SCEPTILE_1, :BLAZIKEN_1, :SWAMPERT_1,
  :GARDEVOIR_1, :SABLEYE_1, :MAWILE_1,
  :AGGRON_1, :MEDICHAM_1, :MANECTRIC_1,
  :SHARPEDO_1, :CAMERUPT_1, :ALTARIA_1,
  :BANETTE_1, :ABSOL_1, :GLALIE_1,
  :SALAMENCE_1, :METAGROSS_1,
  :LATIAS_1, :LATIOS_1,
  :GROUDON_1, :KYOGRE_1, :RAYQUAZA_1,
  :LOPUNNY_1, :GARCHOMP_1, :LUCARIO_1,
  :ABOMASNOW_1, :GALLADE_1, 
  :AUDINO_1,
  :GRENINJA_1, :GRENINJA_2,
  :DIANCIE_1,
  :DIALGA_1, :PALKIA_1, :GIRATINA_1,
  :ARCEUS, :ARCEUS_1, :ARCEUS_2,
  :ARCEUS_3, :ARCEUS_4, :ARCEUS_5,
  :ARCEUS_6, :ARCEUS_7, :ARCEUS_8,
  :ARCEUS_9, :ARCEUS_10, :ARCEUS_11,
  :ARCEUS_12, :ARCEUS_13, :ARCEUS_14,
  :ARCEUS_15, :ARCEUS_16, :ARCEUS_17,
  :ARCEUS_18,
  :MIMIKYU_1,
  :NECROZMA_3, :NECROZMA_4,
  :CRAMORANT_1, :CRAMORANT_2,
  :ALCREMIE_8, :ALCREMIE_9, :ALCREMIE_10,
  :ALCREMIE_11, :ALCREMIE_12, :ALCREMIE_13,
  :ALCREMIE_15, :ALCREMIE_16, :ALCREMIE_17,
  :ALCREMIE_18, :ALCREMIE_19, :ALCREMIE_20,
  :ALCREMIE_22, :ALCREMIE_23, :ALCREMIE_24,
  :ALCREMIE_25, :ALCREMIE_26, :ALCREMIE_27,
  :ALCREMIE_29, :ALCREMIE_30, :ALCREMIE_31,
  :ALCREMIE_32, :ALCREMIE_33, :ALCREMIE_34,
  :ALCREMIE_36, :ALCREMIE_37, :ALCREMIE_38,
  :ALCREMIE_39, :ALCREMIE_40, :ALCREMIE_41,
  :ALCREMIE_43, :ALCREMIE_44, :ALCREMIE_45,
  :ALCREMIE_46, :ALCREMIE_47, :ALCREMIE_48,
  :ALCREMIE_50, :ALCREMIE_51, :ALCREMIE_52,
  :ALCREMIE_53, :ALCREMIE_54, :ALCREMIE_55,
  :ALCREMIE_57, :ALCREMIE_58, :ALCREMIE_59,
  :ALCREMIE_60, :ALCREMIE_61, :ALCREMIE_62,
  :EISCUE_1, :MORPEKO_1,
  :F00, :F00_1,
  :MT, :MT2,
  :HUMANOID
]

# An array of possible Items
ITEM_WHITELIST = [
  :HYPERPOTION,
  :MAXPOTION,
  :FULLRESTORE,
  :XATTACK,
  :XDEFENSE,
  :XSPATK,
  :XSPDEF,
  :XSPEED,
  :XACCURACY,
  :DIREHIT,
  :FULLHEAL
]

# An array of all viable trainer classes
# [CLASS, Overworld, Preferred types / species]
RT_TRAINER_WHITELIST = [
  [:ACETRAINER_M,"trainer_ACETRAINER_M"],
  [:ACETRAINER_F,"trainer_ACETRAINER_F"],
  [:AROMALADY,"trainer_AROMALADY",:GRASS],
  [:BACKPACKER_M,"trainer_BACKPACKER_M",:NORMAL,:ROCK,:GROUND],
  [:BACKPACKER_F,"trainer_BACKPACKER_F",:NORMAL,:ROCK,:GROUND],
  [:BAKER,"trainer_BAKER",:GRASS,:FIRE,:WATER],
  [:BEAUTY,"trainer_BEAUTY",:NORMAL,:ELECTRIC,:GRASS,:WATER,:FAIRY],
  [:BIKER,"trainer_BIKER",:POISON,:DARK],
  [:BIRDKEEPER_M,"trainer_BIRDKEEPER_M",:FLYING],
  [:BIRDKEEPER_F,"trainer_BIRDKEEPER_F",:FLYING],
  [:BLACKBELT,"trainer_BLACKBELT",:FIGHTING],
  [:BATTLEGIRL,"trainer_BATTLEGIRL",:FIGHTING],
  [:BUGCATCHER,"trainer_BUGCATCHER",:BUG],
  [:BURGLAR,"trainer_BURGLAR",:DARK,:FIRE,:KOFFING,:WEEZING,:NICKIT,:THIEVUL],
  [:CAMPER,"trainer_CAMPER",:NORMAL,:FAIRY,:GRASS,:ELECTRIC,:GROUND],
  [:PICNICKER,"trainer_PICNICKER",:NORMAL,:FAIRY,:GRASS,:ELECTRIC,:GROUND],
  [:CYCLIST_M,"trainer_CYCLIST_M",:FLYING,:ELECTRIC],
  [:CYCLIST_F,"trainer_CYCLIST_F",:FLYING,:ELECTRIC],
  [:DANCER,"trainer_DANCER",:FIRE,:ELECTRIC,:PSYCHIC,:GHOST],
  [:DOCTOR,"trainer_DOCTOR",:NORMAL,:PSYCHIC,:BUG,:AUDINO,:CHANSEY,:BLISSEY],
  [:NURSE,"trainer_NURSE",:NORMAL,:PSYCHIC,:BUG,:AUDINO,:CHANSEY,:BLISSEY],
  [:DRAGONTAMER,"trainer_DRAGONTAMER",:DRAGON],
  [:ENGINEER,"trainer_ENGINEER",:ELECTRIC,:STEEL],
  [:FAIRYTALEGIRL,"trainer_FAIRYTALEGIRL",:FAIRY],
  [:FIREBREATHER,"trainer_FIREBREATHER",:FIRE],
  [:FISHERMAN,"trainer_FISHERMAN",:WATER],
  [:GAMBLER,"trainer_GAMBLER",:DARK],
  [:GENTLEMAN,"trainer_GENTLEMAN",:NORMAL,:GROWLITHE,:ARCANINE,:LILLIPUP,:HERDIER,:STOUTLAND,:ROCKRUFF,:LYCANROC,:YAMPER,:BOLTUND],
  [:MADAME,"trainer_MADAME",:NORMAL,:MEOWTH,:PERSIAN,:SKITTY,:DELCATTY,:GLAMEOW,:PURUGLY,:PURRLOIN,:LIEPARD],
  [:GUITARIST_M,"trainer_GUITARIST_M",:ELECTRIC,:ROCK,:WHISMUR,:LOUDRED,:EXPLOUD],
  [:GUITARIST_F,"trainer_GUITARIST_F",:POISON,:STEEL,:WHISMUR,:LOUDRED,:EXPLOUD],
  [:HARLEQUIN,"trainer_HARLEQUIN",:PSYCHIC,:BUG],
  [:HEXMANIAC,"trainer_HEXMANIAC",:GHOST,:PSYCHIC],
  [:HIKER,"trainer_HIKER",:ROCK,:GROUND],
  [:HOOPSTER,"trainer_HOOPSTER",:ELECTRIC,:BUG],
  [:JANITOR,"trainer_JANITOR",:POISON,:TRUBBISH,:GARBODOR,:MINCCINO,:CINCCINO],
  [:JUGGLER,"trainer_JUGGLER",:PSYCHIC,:VOLTORB,:ELECTRODE],
  [:KIMONOGIRL,"trainer_KIMONOGIRL",:FAIRY,:STEEL,:EEVEE,:VAPOREON,:JOLTEON,:FLAREON,:ESPEON,:UMBREON,:LEAFEON,:GLACEON,:SYLVEON],
  [:LINEBACKER,"trainer_LINEBACKER",:FIGHTING,:FIRE],
  [:MAID,"trainer_MAID",:NORMAL,:STEEL,:FAIRY,:INDEEDEE,:SINISTEA,:POLTEAGEIST],
  [:MUSICIAN,"trainer_MUSCICIAN",:ELECTRIC,:NORMAL],
  [:NURSERYAIDE,"trainer_NURSERYAIDE",:NORMAL,:BUG],
  [:OFFICEWORKER_M,"trainer_OFFICEWORKER_M",:NORMAL,:GRASS,:ICE],
  [:OFFICEWORKER_M2,"trainer_OFFICEWORKER_M2",:DRAGON,:STEEL,:ELECTRIC],
  [:OFFICEWORKER_F,"trainer_OFFICEWORKER_F",:NORMAL,:FIRE,:ICE],
  [:PAINTER,"trainer_PAINTER",:SMEARGLE,:SUNFLORA,:SIGILYPH,:NORMAL,:GRASS],
  [:PARASOLLADY,"trainer_PARASOLLADY",:NORMAL,:WATER],
  [:PILOT,"trainer_PILOT",:STEEL,:FLYING],
  [:PITCHER,"trainer_PITCHER",:GROUND,:FLYING],
  [:POKEFAN_M,"trainer_POKEFAN_M",:NORMAL,:GRASS,:FIRE,:WATER,:ELECTRIC,:BUG],
  [:POKEFAN_F,"trainer_POKEFAN_F",:NORMAL,:GRASS,:FIRE,:WATER,:ELECTRIC,:BUG],
  [:POKEMANIAC,"trainer_POKEMANIAC",:ELECTRIC,:GROUND,:WATER,:ROCK],
  [:POKEMONBREEDER_M,"trainer_POKEMONBREEDER_M",:NORMAL,:PICHU,:TOGEPI,:IGGLYBUFF,:CLEFFA,:RIOLU,:CHINGLING,:TYROGUE,:SMOOCHUM,
    :ELEKID,:MAGBY,:AZURILL,:WYNAUT,:BUDEW,:BONSLY,:MIMEJR,:HAPPINY,:MUNCHLAX,:MANTYKE],
  [:POKEMONBREEDER_F,"trainer_POKEMONBREEDER_F",:NORMAL,:PICHU,:TOGEPI,:IGGLYBUFF,:CLEFFA,:RIOLU,:CHINGLING,:TYROGUE,:SMOOCHUM,
    :ELEKID,:MAGBY,:AZURILL,:WYNAUT,:BUDEW,:BONSLY,:MIMEJR,:HAPPINY,:MUNCHLAX,:MANTYKE],
  [:POKEMONRANGER_M,"trainer_POKEMONRANGER_M",:WATER,:GRASS,:GROUND,:DRAGON,:MINUN],
  [:POKEMONRANGER_F,"trainer_POKEMONRANGER_F",:WATER,:GRASS,:GROUND,:DRAGON,:PLUSLE],
  [:POLICE,"trainer_POLICE",:FIRE,:FIGHTING,:GROWLITHE,:ARCANINE,:LILLIPUP,:HERDIER,:STOUTLAND,:ROCKRUFF,:LYCANROC,:YAMPER,:BOLTUND],
  [:PRESCHOOLER_M,"trainer_PRESCHOOLER_M",:NORMAL,:RATTATA,:SENTRET,:ZIGZAGOON,:BIDOOF,:PATRAT,:LILLIPUP,:BUNNELBY,:YUNGOOS,:WOOLOO],
  [:PRESCHOOLER_F,"trainer_PRESCHOOLER_F",:NORMAL,:RATTATA,:SENTRET,:ZIGZAGOON,:BIDOOF,:PATRAT,:LILLIPUP,:BUNNELBY,:YUNGOOS,:WOOLOO],
  [:PSYCHIC_M,"trainer_PSYCHIC_M",:PSYCHIC],
  [:PSYCHIC_F,"trainer_PSYCHIC_F",:PSYCHIC],
  [:RAILSTAFF,"trainer_RAILSTAFF",:ROCK,:STEEL,:FIRE],
  [:RICHBOY,"trainer_RICHBOY",:NORMAL],
  [:LADY,"trainer_LADY",:NORMAL],
  [:ROUGHNECK,"trainer_ROUGHNECK",:FIGHTING,:DARK],
  [:RUINMANIAC,"trainer_RUINMANIAC",:GROUND,:ROCK,:KABUTO,:KABUTOPS,:OMANYTE,:OMASTAR,:AERODACTYL,:LILEEP,:CRADILY,:ANORITH,
    :ARMALDO,:RELICANTH,:CRANDIOS,:RAMPARDOS,:SHIELDON,:BASTIODON,:TIRTOUGA,:CARRACOSTA,:ARCHEN,:ARCHEOPS,:TYRUNT,:TYRANTRUM,:AMAURA,:AURORUS],
  [:SAILOR,"trainer_SAILOR",:WATER,:FIGHTING],
  [:SCHOOLKID_M,"trainer_SCHOOLKID_M",:NORMAL,:PSYCHIC],
  [:SCHOOLKID_F,"trainer_SCHOOLKID_F",:NORMAL,:PSYCHIC],
  [:SCIENTIST_M,"trainer_SCIENTIST_M",:ELECTRIC,:POISON],
  [:SCIENTIST_F,"trainer_SCIENTIST_F",:ELECTRIC,:POISON],
  [:SKIER_M,"trainer_SKIER_M",:ICE],
  [:SKIER_F,"trainer_SKIER_F",:ICE],
  [:SMASHER,"trainer_SMASHER",:ELECTRIC,:GRASS,:ELECTRIC,:WATER],
  [:STRIKER,"trainer_STRIKER",:FIGHTING,:FLYING,:DARK,:FIRE],
  [:SUPERNERD,"trainer_SUPERNERD",:ELECTRIC,:STEEL],
  [:TUBER_M,"trainer_TUBER_M",:WATER],
  [:TUBER_F,"trainer_TUBER_F",:WATER],
  [:VETERAN_M,"trainer_VETERAN_M"],
  [:VETERAN_F,"trainer_VETERAN_F"],
  [:WAITER,"trainer_WAITER",:NORMAL,:PSYCHIC,:INDEEDEE],
  [:WAITRESS,"trainer_WAITRESS",:NORMAL,:PSYCHIC,:INDEEDEE],
  [:WORKER,"trainer_WORKER",:ROCK,:FIGHTING,:STEEL,:GROUND],
  [:WORKER2,"trainer_WORKER2",:FIGHTING,:STEEL,:ICE],
  [:YOUNGSTER,"trainer_YOUNGSTER",:NORMAL,:RATTATA],
  [:LASS,"trainer_LASS",:NORMAL]
]

# An array of all viable gym leader classes
# [CLASS, Overworld, Preferred types / species]
RT_LEADER_WHITELIST = [
  [:LEADER_Hongxin,"trainer_LEADER_Xin",:PSYCHIC],
  [:LEADER_Huangxin,"trainer_LEADER_Xin",:PSYCHIC],
  [:LEADER_Amanda,"trainer_LEADER_Amanda",:ROCK],
  [:LEADER_Calix,"trainer_LEADER_Calix",:WATER],
  [:LEADER_Benjamin,"trainer_LEADER_Benjamin",:FAIRY],
  [:LEADER_Patriama,"trainer_LEADER_Patriama",:GHOST],
  [:LEADER_Angeline,"trainer_LEADER_Angeline",:ICE],
  [:LEADER_Leonard,"trainer_LEADER_Leonard",:DARK],
  [:LEADER_Yira,"trainer_LEADER_Yira",:DRAGON],
  [:LEADER_Emilia,"trainer_LEADER_Emilia",:FIGHTING]
]

# An array of all viable rival classes
# [CLASS, Overworld, Preferred types / species]
RT_RIVAL_WHITELIST = [
  [:RIVAL_Giltbert,"trainer_RIVAL1",:ELECTRIC,:DRAGON,:NORMAL,:WATER,:FIGHTING,:STEEL,:FIRE,:GRASS,:GROUND,:AMPHAROS],
  [:RIVAL_Diana,"trainer_RIVAL2",:FAIRY,:WATER,:FIGHTING,:GRASS,:POISON,:FIRE,:GHOST,:DARK,:DRAGON,:SYLVEON]
]